from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class TransactionBase(BaseModel):
    id: Optional[str] = None # Generated by server if null
    amount: float = 0.0
    description: Optional[str] = None
    category: Optional[str] = "General"
    type: Optional[str] = "expense" # 'income' or 'expense'
    payment_mode: Optional[str] = None
    date: Optional[datetime] = None

class TransactionCreate(TransactionBase):
    user_id: str

class TransactionUpdate(BaseModel):
    amount: Optional[float] = None
    description: Optional[str] = None
    category: Optional[str] = None
    type: Optional[str] = None
    payment_mode: Optional[str] = None
    date: Optional[datetime] = None

class TransactionInDB(TransactionBase):
    user_id: str
    user_name: Optional[str] = None
    user_email: Optional[str] = None
    user_phone: Optional[str] = None
    created_at: Optional[datetime] = None

    class Config:
        from_attributes = True
