from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class TransactionBase(BaseModel):
    id: Optional[str] = None # Generated by server if null
    amount: float
    description: Optional[str] = None
    category: str
    type: str # 'income' or 'expense'
    payment_mode: Optional[str] = None
    date: datetime

class TransactionCreate(TransactionBase):
    user_id: str

class TransactionUpdate(BaseModel):
    amount: Optional[float] = None
    description: Optional[str] = None
    category: Optional[str] = None
    type: Optional[str] = None
    payment_mode: Optional[str] = None
    date: Optional[datetime] = None

class TransactionInDB(TransactionBase):
    user_id: str
    created_at: datetime

    class Config:
        from_attributes = True
